# Generated by Django 3.2 on 2021-05-04 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=1000)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('group', models.CharField(max_length=20)),
                ('bike', models.BooleanField(default=False)),
                ('car', models.BooleanField(default=False)),
                ('boat', models.BooleanField(default=False)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('years', models.BooleanField()),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('amount', models.FloatField()),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
